* be more convenient, by supporting mulle-fetch <url>

diff --git a/mulle-fetch b/mulle-fetch
--- a/mulle-fetch
+++ b/mulle-fetch
@@ -34,7 +34,7 @@ then
    set -x
 fi
 
-MULLE_EXECUTABLE_VERSION="1.3.8"
+MULLE_EXECUTABLE_VERSION="1.4.0"
 
 
 MULLE_EXECUTABLE_BASHFUNCTIONS="1.3"
@@ -298,8 +298,24 @@ main()
       ;;
 
       *)
-         log_error "Unknown command \"${cmd}\""
-         usage "${MULLE_TRACE}"
+         [ "$#" -eq 0 ] || _usage
+
+         # shellcheck source=src/mulle-fetch-commands.sh
+         . "${MULLE_FETCH_LIBEXEC_DIR}/mulle-fetch-commands.sh"
+         . "${MULLE_FETCH_LIBEXEC_DIR}/mulle-fetch-url.sh"
+
+         local scmtype
+
+         scmtype="`fetch_typeguess_main "${cmd}"`"
+         scmtype="${scmtype:-git}"
+
+         if ! dstdir="`fetch_guess_main -s "${scmtype}" "${cmd}"`"
+         then
+            fail "Failed to guess project name from url \"${cmd}\""
+         fi
+
+         log_info "Fetching into ${C_RESET_BOLD}${dstdir}"
+         fetch_clone_main -s "${scmtype}" "${cmd}" "${dstdir}"
       ;;
    esac
 }
