....and fix .travis.yml

diff --git a/tests/run-test b/tests/run-test
--- a/tests/run-test
+++ b/tests/run-test
@@ -23,16 +23,16 @@ main()
    OUTPUT_DEVICE=
    for i in "${TEST_DIR}"/*
    do
-      if [ -x "$i/run-test.sh" ]
+      if [ -x "$i/run-test" ]
       then
          log_verbose "------------------------------------------"
          log_info    "$i:"
          log_verbose "------------------------------------------"
          if [ "${MULLE_FLAG_LOG_TERSE}" = "YES" ]
          then
-            ( cd "$i" && ./run-test.sh "$@" > /dev/null 2>&1 ) || fail "Test \"$i\" failed"
+            ( cd "$i" && ./run-test "$@" > /dev/null 2>&1 ) || fail "Test \"$i\" failed"
          else
-            ( cd "$i" && ./run-test.sh "$@" ) || fail "Test \"$i\" failed"
+            ( cd "$i" && ./run-test "$@" ) || fail "Test \"$i\" failed"
          fi
       fi
    done
